"""add user table

Revision ID: 050bf9cff91a
Revises: a2af57c490a2
Create Date: 2022-01-19 14:06:14.177003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050bf9cff91a'
down_revision = 'a2af57c490a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hashed', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
